### ISSUE TITLE
Internal error.

### ISSUE THREAD

**Issue by PotatoPutato** [hammy2899/ArchonCrates#11]
When i use /archoncrates create, i get "An internal error occured while attempting to perform this command"
Here is the error from when i executed the command.
https://pastebin.com/ybnS4uG8
pls help

**Comment by y0hami** [comment]
Hi PotatoPutato,

This is due to an error in your config, it is trying to cast something to an integer like a string or boolean.

**Comment by PotatoPutato** [comment]
how do i find what string is the error?

**Comment by y0hami** [comment]
If you post a snippet of your keys, crates and prizes configs here I will take a look. You can also use our file references on the website to help see what data types are used for each variable in the configs.

Website: https://archoncrates.com

**Comment by PotatoPutato** [comment]
https://pastebin.com/mtVwmkg7

**Comment by y0hami** [comment]
The problem is that your `GodApple` prize the chance is `10` and it is expecting a double so you need to change it to `10.0`

**Comment by PotatoPutato** [comment]
thx
