### ISSUE TITLE
No items given

### ISSUE THREAD

**Issue by Zhypo** [hammy2899/ArchonCrates#12]
Hi,

I've changed most things to custom make it for my server.

However, when I use a default key they will not open in a default crate.
And I will not get any items if I win a certain prize, nor do the commands work.

Crates File: https://pastebin.com/VSPJJzY5
Keys: https://pastebin.com/X3JnY1Uq

Thanks in advance

**Comment by y0hami** [comment]
Hi Zhypo,

What version of ArchonCrates and what server software are you using?

**Comment by Zhypo** [comment]
I'm using a localhost spigot 1.8 and the latest version of archoncrates

**Comment by y0hami** [comment]
Did you use any of the previous versions of ArchonCrates and are you using the configuration files from the previous version?

**Comment by Zhypo** [comment]
I downloaded the plugin 5-6 days ago, so should all be the latest version, right?

**Comment by y0hami** [comment]
The configuration files don't match the newest version of ArchonCrates and the latest version is not tested nor does it support Minecraft 1.8

**Comment by Zhypo** [comment]
Oh, so what version should I download for it to work on 1.8? If there is any 1.8 supported

**Comment by y0hami** [comment]
The latest version of ArchonCrates which supports Minecraft 1.8 is v17.3

Download: https://dev.bukkit.org/projects/archoncrates/files/906197

_Keep in mind we don't offer support for this version anymore!_
