### ISSUE TITLE
Look into NBT tags

### ISSUE THREAD

**Issue by y0hami** [hammy2899/ArchonCrates#15]
Take a look at NBT tags for keys and crates to keep better track of what key and crate is what and who owns them etc...

**Comment by smellyonionman** [comment]
I've spent the evening desperately looking for ways to integrate physical crates into freshly generated BO3 objects, before the chunks are generated.  I feel like I am so close... but I'm not even 100% sure if it's possible.  With the generation and block ID *and* data folder changes coming to 1.13 however, I am feeling optimistic that this will happen soon.

If this is possible already please find a moment to drop me a line!  I am about ready to call it impossible, for the time.  But the NBT tags would probably help, no?

**Comment by y0hami** [comment]
@adamlaughlin I have never tried doing anything like that but I would assume NBT tags would possibly help. I am quite busy at the moment so I won't be adding NBT tags for a while.

**Comment by smellyonionman** [comment]
I've started writing the plugin, I will support ArchonCrates.
