### ISSUE TITLE
No Chests on Create Menu

### ISSUE THREAD

**Issue by SKILLSHOTZZZYT** [hammy2899/ArchonCrates#18]
Whenever I try to put in some custom crate items and other stuff. It does allow me to create any Crates. The GUI is glitched. Please fix ASAP!

https://pastebin.com/BcUvJHd8

- Thank you very much :)

Also, I have another question, Is it possible to configure it to randomly drop default crate keys whenever the player kills a user in a PvP World?

**Comment by SKILLSHOTZZZYT** [comment]
![image](https://user-images.githubusercontent.com/36327945/36061143-e92bbb4e-0e4d-11e8-9f8a-f1afde97848e.png)
This is what it looks like when i try to create new crates

**Comment by y0hami** [comment]
Please can you supply the following information
- Server Software (Spigot, Bukkit etc.)
- Server Version (1.7, 1.8 etc)
- Java Version (1.7, 1.8)
- Host (Windows, Linux, Hosting Platform like mcprohosting)

**Comment by SKILLSHOTZZZYT** [comment]
Server Software: Spigot
Version: v1.12.1 (Will soon include ViaVersion and ViaVersionBelow)
Java Version: Not too sure, Shouldnt be necessary for this error anyway.
Host: HostHorde

The error pops up whenever i edit the crates.yml file.

**Comment by y0hami** [comment]
I have done a little testing and have found that the error is not in your `crates.yml` file but in your `prizes.yml`. 

The prize `jackolantern` you have a single quote in the name
```
name: '&6Jack o' Lantern Hat Cosmetic'
```
you can fix this by changing the name to this
```
name: "&6Jack o' Lantern Hat Cosmetic"
```

**Comment by SKILLSHOTZZZYT** [comment]
Ah! That was it?! Well then, I feel stupid. Thanks for your help :)

**Comment by y0hami** [comment]
No problem, in the future try checking your server console for errors 9/10 it will tell you whats wrong and also try running your files through [yamllint](http://www.yamllint.com/) to check if there valid.
