### ISSUE TITLE
Issue when I do /archoncrates create

### ISSUE THREAD

**Issue by AtheresG** [hammy2899/ArchonCrates#20]
When I do the command /archoncrates create it says "An internal error has occurred... Will you help me?

-AtheresG

**Comment by y0hami** [comment]
Can you provide the following information:
- Server OS (Linux, Windows, Server Host like MCProHosting)
- Server software (Spigot, Bukkit etc)
- ArchonCrates version,
- Java version (If you have it)
- Link to keys, crates, prizes config files via [pastebin.com](https://pastebin.com/)

**Comment by AtheresG** [comment]
OS - FalloutHousting
Software - PaperSpigot 1.8.8
Version - 19.1.2
Keys - https://pastebin.com/mZqiqjD7
Crates - https://pastebin.com/SvW14yxp
Prizes - https://pastebin.com/6D9umHJk

**Comment by y0hami** [comment]
This issue might be caused because you are running a version of Minecraft which ArchonCrates v19 does not support. ArchonCrates v19 only supports Minecraft version 1.12.*

**Comment by AtheresG** [comment]
I can't find the version for 1.8

**Comment by y0hami** [comment]
Here is a version which is officially built for 1.8 https://dev.bukkit.org/projects/archoncrates/files/906197

**Comment by AtheresG** [comment]
Will it be out of date tho?

**Comment by AtheresG** [comment]
With the plugin how do I set up to be like the crates on the archon

**Comment by y0hami** [comment]
We don't offer support for out of date plugins we only offer it for the latest version, if you run into any issues with them its down to you to solve, if you want to use the latest version you must update your server software to support the latest version of Minecraft.

We do have plans to release a version of 19 which supports Minecraft 1.7, 1.8, 1.9, 1.10, 1.11 and 1.12 but this will be in a few months.
