### ISSUE TITLE
Issue With Perms

### ISSUE THREAD

**Issue by AtheresG** [hammy2899/ArchonCrates#21]
I gave my members the perm archoncrates.crate.use or archoncrates.command.use but it still says 'You do not have the permission to open/use a virtual crate

**Comment by y0hami** [comment]
Make sure you are using the correct permission for the correct version of the plugin.

**Comment by AtheresG** [comment]
What is the correct permission for v17.3

**Comment by y0hami** [comment]
Here is a list of all permissions for v17.3

| Access                     | Permission                          |
|----------------------------|-------------------------------------|
| COMMAND_HELP               | archoncrates.command.help           |
| COMMAND_REMOVE             | archoncrates.command.remove         |
| COMMAND_INFO               | archoncrates.command.info           |
| COMMAND_KEYS               | archoncrates.command.keys           |
| COMMAND_VKEYS              | archoncrates.command.vkeys          |
| COMMAND_CRATES             | archoncrates.command.crates         |
| COMMAND_FILES              | archoncrates.command.files          |
| COMMAND_UPDATE             | archoncrates.command.update         |
| COMMAND_CREATE             | archoncrates.command.create         |
| COMMAND_CREATE_VIRTUAL     | archoncrates.command.create.virtual |
| COMMAND_RELOAD             | archoncrates.command.reload         |
| COMMAND_CRATE              | archoncrates.command.crate          |
| COMMAND_KEY                | archoncrates.command.key            |
| COMMAND_KEY_ALL            | archoncrates.command.key.all        |
| COMMAND_VIRTUAL_KEYS       | archoncrates.command.vkey           |
| COMMAND_VIRTUAL_KEYS_ALL   | archoncrates.command.vkey.all       |
| COMMAND_REMOVE_VIRTUAL_KEY | archoncrates.command.remove.vkey    |
| COMMAND_HISTORY            | archoncrates.command.history        |
| COMMAND_VOUCHER_NEW        | archoncrates.command.voucher.new    |
| COMMAND_VOUCHER_REDEEM     | archoncrates.command.voucher.redeem |
| COMPLETE_TAB               | archoncrates.completetab            |
| OPEN_CRATE_WITH_ANY_KEY    | archoncrates.crate.open.any         |
| OPEN_CRATE                 | archoncrates.crate.open             |
| OPEN_VIRTUAL_CRATE         | archoncrates.crate.open.virtual     |
| VIEW_PRIZES                | archoncrates.view.priszes           |
| BREAK_CRATE                | archoncrates.event.break.crate      |
| SIGN_USE_BUY               | archoncrates.sign.use.buy           |
| SIGN_CREATE_NORAML         | archoncrates.sign.create            |
| SIGN_CREATE_VIRTUAL        | archoncrates.sign.create.virtual    |
| SIGN_BREAK                 | archoncrates.sign.break             |

**Comment by AtheresG** [comment]
My tester can't open the virtual crate in v17.3 even when I gave him the command OPEN_VIRTUAL_CRATE

**Comment by AtheresG** [comment]
*tester

**Comment by AtheresG** [comment]
Can you also set a percentage of the person getting a certain item?

**Comment by y0hami** [comment]
Take a look at these videos, they may help you
https://www.youtube.com/watch?v=70hsPdsd_LA
https://www.youtube.com/watch?v=Bo5_5b9-xY4
