### ISSUE TITLE
The Virtual Crate isn't Opening 

### ISSUE THREAD

**Issue by AtheresG** [hammy2899/ArchonCrates#22]
Whenever I right-click the cratev it doesn't do or say anything in chat.

Below are links to the configs that I have edited and I am using v17.3. If you need anything else message me

Virtual Keys - https://pastebin.com/hCnNPaLb

Crate Loot - https://pastebin.com/xtjbnYGW

**Comment by AtheresG** [comment]
This is what it says in the console

https://pastebin.com/cGh6zLhm

**Comment by y0hami** [comment]
We don't offer support for older versions as mentioned https://github.com/hammy2899/ArchonCrates/issues/20#issuecomment-368228059
