### ISSUE TITLE
Please Help

### ISSUE THREAD

**Issue by AtheresG** [hammy2899/ArchonCrates#23]
I know that you are getting annoyed that I am having so much trouble with he plugin but will you please tell me how to fix this error?

https://pastebin.com/pYt20gRE

**Comment by y0hami** [comment]
Please provide the full console error, if you can upload the log file from the `logs/` directory.

**Comment by AtheresG** [comment]
[Logs.zip](https://github.com/hammy2899/ArchonCrates/files/1787482/Logs.zip)

**Comment by AtheresG** [comment]
Here is the whole file if you didn't get what you needed
[ArchonCrates.zip](https://github.com/hammy2899/ArchonCrates/files/1787484/ArchonCrates.zip)

**Comment by AtheresG** [comment]
Do the prizes have to equal something?

**Comment by y0hami** [comment]
Sorry, I should have specified I need the server logs, not ArchonCrates.

Also, the prizes DO NOT have to add up to anything in 17.* this was a requirement in early versions.

**Comment by AtheresG** [comment]
[logs.zip](https://github.com/hammy2899/ArchonCrates/files/1791535/logs.zip)

**Comment by AtheresG** [comment]
That should be the right one

**Comment by AtheresG** [comment]
you there?

**Comment by y0hami** [comment]
This error is due to errors in your config files, try checking them on a yaml validator and check over them

**Comment by AtheresG** [comment]
I have checked them and it says nothing useful

**Comment by y0hami** [comment]
The error suggest you have a <kbd>TAB</kbd> character in your file
```
[17:32:46] [Server thread/ERROR]: Cannot load plugins/ArchonCrates/Crate/virtual keys.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 140, column 1:
    	
    ^
```
