### ISSUE TITLE
Remote key rewards

### ISSUE THREAD

**Issue by morgan2233** [hammy2899/ArchonCrates#24]
hello i run a bungee server and want to know if theres away to link them so i can give key awards as a award for winning the mini games

**Comment by y0hami** [comment]
Currently no there isn't but I did think about a similar situation and was thinking of adding away to give offline players keys which would be a perfect solution for you. I am going to add something like this for the next release. In the mean time I can only suggest making a custom plugin to push rewards to a SQL database using a web api then having a custom plugin check when a player connects.

**Comment by y0hami** [comment]
End of Life Statement
Please read the following statement: [EOL_STATEMENT.md](https://github.com/hammy2899/ArchonCrates/blob/4125fbfc764db261f7fad6301b5aa66dc04ff131/EOL_STATEMENT.md)
