### ISSUE TITLE
Please help and respond

### ISSUE THREAD

**Issue by AtheresG** [hammy2899/ArchonCrates#25]
My crate (virtual) won't open at all and keeps having the error 'PlayerInteractEvent'

**Comment by y0hami** [comment]
Can you provide your logs and files

**Comment by AtheresG** [comment]
[ArchonCrates(Original).zip](https://github.com/hammy2899/ArchonCrates/files/1809208/ArchonCrates.Original.zip)
[ArchonCrates.zip](https://github.com/hammy2899/ArchonCrates/files/1809194/ArchonCrates.zip)
[logs.zip](https://github.com/hammy2899/ArchonCrates/files/1809206/logs.zip)

**Comment by AtheresG** [comment]
Anything else?

**Comment by y0hami** [comment]
Your `virtual keys.yml` file has a tab character in it
```
[18:44:21] [Server thread/ERROR]: Cannot load plugins/ArchonCrates/Crate/virtual keys.yml
org.bukkit.configuration.InvalidConfigurationException: while scanning for the next token
found character 	 '\t(TAB)' that cannot start any token. (Do not use \t(TAB) for indentation)
 in 'string', line 67, column 1:
```
