### ISSUE TITLE
Thousands of console entries

### ISSUE THREAD

**Issue by LarryNewmanMC** [hammy2899/ArchonCrates#30]
My console is being spammed with
[02:15:57] [Server thread/INFO]: [ArchonCrates] Error: There was a request to a value which did not exist.
[02:15:57] [Server thread/INFO]:                       File: prizes.yml
[02:15:57] [Server thread/INFO]:                       Path: Prizes.DevHead.name

This is a snippet of the server log https://pastebin.com/rpfnJpQa

I've been through everything I can think of and I'm not sure how to correct this error

**Comment by y0hami** [comment]
This is an error in your configuration, the error suggests that one of your crates contains the `DevHead` prize but the prize doesn't have a `name` field in the `prizes.yml` file.

**Comment by LarryNewmanMC** [comment]
Thank you for the response. I see where I was going wrong. I was focusing pretty much 100% on crates.yml, but then I recalled that there are also virtual crates, which is what the error is coming from. We edited a lot of the prizes and the error was coming from virtual crate.yml. Thank you for the help, it's all fixed now.

**Comment by y0hami** [comment]
Good to hear!
