### ISSUE TITLE
The GUI doesn't work

### ISSUE THREAD

**Issue by WolfGameStudios** [hammy2899/ArchonCrates#31]
I used `/achroncrates create` and a gui popped up but when I clicked something, rather than the gui taking me anywhere I just grabbed the item.

**Comment by y0hami** [comment]
Can you send a snippet of your server log file and what version of AC your using?

**Comment by WolfGameStudios** [comment]
I choose a different crate plugin but thanks for offering support, Sorry for replying 10 days latter, I forgot I even asked for support to be honest.
