### ISSUE TITLE
[Support] Issue when I do /archoncrates create.

### ISSUE THREAD

**Issue by AngelOfCreation** [hammy2899/ArchonCrates#4]
When I do the command, /archoncrates create, it says this in chat: "An internal error has occurred while attempting to perform this command" and also when I do it I get this long message in my console:

https://pastebin.com/sTpanwHP

/archoncrates help, crates, and key works just fine but create doesn't. At first I realized that I had a fatality crate but not a key so I added that and it still didn't work.

-66Herobrine66

**Comment by y0hami** [comment]
Hi 66Herobrine66,

This is an issue in your configuration, please can you make a pastebin of your configuration files.

**Comment by AngelOfCreation** [comment]
Ok which one? the main ones ive been modifying is keys crates and prizes. Should I just make a pastebin of them all?

-66Herobrine66

**Comment by y0hami** [comment]
Please send all 3, keys, crates and prizes.

**Comment by AngelOfCreation** [comment]
https://pastebin.com/GCZpPhbh
https://pastebin.com/UxZUTtR6
https://pastebin.com/Lc17ZkSh
Here you go.

**Comment by AngelOfCreation** [comment]
Sorry I didn't respond sooner, Was in game testing things.

**Comment by y0hami** [comment]
Ok so in your `prizes.yml` file for each prize you specify an item ID to show in the crate as the prize. You have entered this correctly for nearly all of your prizes apart from 7 of them, spawner prizes I think.

You have entered `ID: 383:52` for the prize `spider` this in an incorrect format. The `item.ID` is the ID of the item and the `item.data` is the data value of the item so you will need to replace

```
item:
      ID: 383:52
      data: 0
```

with

```
item:
      ID: 383
      data: 52
```

on spider prize and all the other prizes you do this with.

**Comment by AngelOfCreation** [comment]
Oh ok I see, Thank you for your help I really appreciate it.
:)

**Comment by y0hami** [comment]
No problem, if you run into another problem reopen this issue or create a new one!

**Comment by AtheresG** [comment]
Hammy 2899 I am having the same problem with the /archoncrates create comman. Will you help me?

**Comment by AtheresG** [comment]
*command

**Comment by y0hami** [comment]
@AtheresG Post links to pastebin
